export const menuItems = [
    {
      label: 'Item',
      icon: 'FcTreeStructure',
      selectedPage: 'arenalist',
      arenaEndPoint: 'items',
      arenaListName: 'number',
      arenaListNumber: 'name',
    },
    {
      label: 'Files',
      icon: 'FcDocument',
      selectedPage: 'arenalist',
      arenaEndPoint: 'files?format=pdf',
      arenaListName: 'number',
      arenaListNumber: 'title',
    },
    {
      label: 'Changes',
      icon: 'FcBiohazard',
      selectedPage: 'arenalist',
      arenaEndPoint: 'changes',
      arenaListName: 'number',
      arenaListNumber: 'title',
    },
    {
      label: 'Requests',
      icon: 'FcInspection',
      selectedPage: 'arenalist',
      arenaEndPoint: 'requests',
      arenaListName: 'number',
      arenaListNumber: 'title',
    },
    {
      label: 'Quality',
      icon: 'FcProcess',
      selectedPage: 'arenalist',
      arenaSearchEndPoint: 'qualityprocesses?template.guid=HZJ27VMR84NJ2L4FZGTM',
      arenaEndPoint: 'qualityprocesses',
      arenaListName: 'number',
      arenaListNumber: 'name',
    },
    {
      label: 'Suppliers',
      icon: 'FcFactory',
      selectedPage: 'arenalist',
      arenaEndPoint: 'suppliers',
      arenaListName: 'name',
      arenaListNumber: 'description',
    },
    {
      label: 'Audit Planner',
      icon: 'FcPlanner',
      selectedPage: 'externalLink',
      arenaEndPoint: '',
      arenaListName: '',
      arenaListNumber: '',
    },
    {
      label: 'Training',
      icon: 'FcGraduationCap',
      selectedPage: 'arenalist',
      arenaEndPoint: 'trainingplans',
      arenaListName: 'number',
      arenaListNumber: 'name',
    },
    {
      label: 'ThingWorx',
      icon: 'FcBarChart',
      selectedPage: 'externalLink',
      arenaEndPoint: '',
      arenaListName: '',
      arenaListNumber: '',
    },
    {
        label: 'Outbound Events',
        icon: 'FcWorkflow',
        selectedPage: 'outbound Events',
        arenaEndPoint: 'outboundevents/XFZINB27OKVTCVEXG1NK/events',
        arenaListName: 'guid',
        arenaListNumber: 'status',
    },
      
  ];
  